### ISSUE TITLE
Moving to sterling Tracking issue

### ISSUE THREAD

**Issue by YaphetKG** [helxplatform/translator-devops#116]
This issue is to track progress and issues uncovered with trying to deploy to sterling. Will add more comments here and notes on fix status.
So far:
1.  [x] Plater 
2. [x] Answer coalesce 
3. [x]  Api Watchdog
4. [x] Aragorn  
5. [x] Aragorn ranker
6. [x] automat 
7. [x] biolink lookup
8. [x] cam-kp-api
9. [x] cam-pipeline-builder
10. [x] cam-pipeline-web-server
11. [x] --chemical-normalization-- (deprecated?)
12. [x] --edge-normalization-- (deprecated) 
13. [x] filter_results_top_n
14. [x] name-lookup
15. [x] Node normalization 
        - [ ] Node normalization loader
        - [ ]  Node normalization web-server
        - [ ]  redis-r3-external 
16. [x] Ontology tools 
17. [x] question rewrite
18. [x] robokop / covidkop
19. [x] robokop-ui-v2
20. [x] smart-bag
21. [x] strider
22. [x] translator workflow runner

**Comment by YaphetKG** [comment]
On **PLATER**:
* All neo4j instances need resource limits defined. Which should be a little bit above the requests assigned
      * Web servers also need resources / currently experiencing Signal 9 on gunicorn workers on startup due to memory limits.

**Comment by YaphetKG** [comment]
- AC 
- Aragorn
- Aragorn-Ranker
- Automat
- Biolink lookup
- Cam-kp-api
- filter_results_top_n
- name-lookup
- NN (currently a new instance is already up in sterling)
- Question RW
- Strider
- Translator workflow runner 
The above services have resources and request limits set up , and have been tested to run on sterling (Chart validation is good) 
Next steps:
- Plater  (Resource config and PV checkup)
- Make all containers non root (Note there are some that have been non-root but need to double check)

**Comment by YaphetKG** [comment]
Node normalization on Mitchell along with its data has been moved. Waiting for confirmation to point nodenormalization-sri.renci.org/docs to that instance currently running on nodenormalization.apps.renci.org

**Comment by YaphetKG** [comment]
Currently I am working on porting Covidkop / robokop chart to sterling

**Comment by YaphetKG** [comment]
Robokop / Covidkop charts are functional and deployed on sterling.
Platers are now moved over to sterling aswell.

**Comment by YaphetKG** [comment]
onto tools is moved to sterling currently at onto.apps.renci.org , that's the last one remaining, will close issue once we assign it onto.renci.org

**Comment by YaphetKG** [comment]
closing issue all have been moved
